- hosts: masters
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=172.31.0.0/16 --ignore-preflight-errors=NumCPU,Mem
      args:
        creates: /etc/kubernetes/admin.conf
        chdir: $HOME

    - name: Ensure kube user exists
      user:
        name: kube
        shell: /bin/bash
        create_home: yes

    - name: Ensure kube user's home directory exists
      become: yes
      file:
        path: "/home/kube"
        state: directory
        owner: kube
        group: kube
        mode: '0755'

    - name: Create .kube directory for kube user
      become: yes
      file:
        path: "/home/kube/.kube"
        state: directory
        mode: '0755'

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube

    - name: install Pod network
      become: yes
      become_user: kube
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml 
      args:
        chdir: $HOME
        
    - name: Get the token for joining the worker nodes
      become: yes
      become_user: kube
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: Print join command
      debug:
        msg: "{{ kubernetes_join_command.stdout }}"


    - name: Copy join command to local file
      delegate_to: localhost
      copy:
        content: "{{ kubernetes_join_command.stdout_lines[0] }}"
        dest: "/tmp/kubernetes_join_command"
        mode: '0777'
