- hosts: 'workers, masters'
  become: yes

  tasks:
    - name: create the kube user account
      user: name=kube append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'kube' to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: 'kube ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Create .ssh directory for kube user
      file:
        path: /home/kube/.ssh
        state: directory
        owner: kube
        group: kube
        mode: '0700'

    - name: Set up authorized key for the kube user
      authorized_key:
        user: kube
        state: present
        key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"

